services:
  frontend:
      build: ./frontend
      container_name: jerney-frontend
      ports:
          - "80:80"
      depends_on:
          - backend
  
  backend:
     build: ./backend
     container_name: jerney-backend   
     ports:
         - "5000:5000"
     env_file:
      - .env
     depends_on:
         - postgres
          
  postgres:
      image: postgres:17-alpine
      container_name: jerney-postgres
      ports:
          - "5432:5432"
      environment:
       POSTGRES_USER: jerney_user
       POSTGRES_PASSWORD: jerney_pass_2026
       POSTGRES_DB: jerney_db

      volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: