apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: jerney
type: Opaque
stringData:
  DB_HOST: jerney-postgres.cunaoy4222y1.us-east-1.rds.amazonaws.com

  DB_PORT: "5432"

  DB_USER: postgres

  DB_PASSWORD: ${db_password}

  DB_NAME: jerney