#k8s/kustomization.yaml

resources:
- namespace/namespace.yaml

- secrets/secrets.yaml

- backend/deployment.yaml
- backend/service.yaml
- backend/hpa.yaml

- frontend/deployment.yaml
- frontend/service.yaml
- frontend/hpa.yaml

- ingress/ingress.yaml